spring:
    cloud.gateway:
        discovery.locator:
            enabled: true
            lower-case-service-id: true
        routes:
            -   id: test
                uri: lb://eclient
                predicates:
                    - Path=/main/test
                    - Method=GET

eureka.client:
    register-with-eureka: false
    fetch-registry: false
