email.sender: demo.order256@gmail.com

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 465
    username: demo.order256@gmail.com
    password: todo

    protocol: smtp
    properties:
      mail:
        smtp: 
          auth: true
          starttls.enable: true
          ssl.enable: true
